[project]
name = "amp-one-server"
version = "0.0.2"
requires-python = ">=3.11"
dependencies = [
  "fastapi>=0.112.0",
  "uvicorn[standard]>=0.30.0",
]

[tool.uvicorn]
host = "0.0.0.0"
port = 8080
factory = false